# --- !Ups

CREATE TABLE "USERS" (
    user_id SERIAL PRIMARY KEY,
    username VARCHAR NOT NULL,
    password VARCHAR NOT NULL,
    firstname VARCHAR NOT NULL,
    lastname VARCHAR NOT NULL,
    email VARCHAR NOT NULL
);

CREATE TABLE "ROOM" (
  room_id SERIAL PRIMARY KEY,
  name VARCHAR NOT NULL
);

CREATE TABLE "ROOMUSERS" (
  room_id INT REFERENCES "ROOM" (room_id) ON UPDATE CASCADE ON DELETE CASCADE,
  user_id INT REFERENCES "USERS" (user_id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT room_user_pkey PRIMARY KEY (room_id, user_id)
);

# --- !Downs

DROP TABLE "USERS";
DROP TABLE "ROOM";
DROP TABLE "ROOMUSERS";